import 'package:flutter/material.dart';

// primary app color for the project
const appPrimaryColor = Color(0xFFF7BE00);

/*
* light and dark color schemes for the project
* do not make changes to any of theme values
* PRs containing changes to these values will be rejected
* auto generated by Material Theme Builder
* https://m3.material.io/theme-builder#/dynamic
 */

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF775A00),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFFFDF99),
  onPrimaryContainer: Color(0xFF251A00),
  secondary: Color(0xFF6A5D3F),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFF4E0BB),
  onSecondaryContainer: Color(0xFF241A04),
  tertiary: Color(0xFF775A00),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFDF99),
  onTertiaryContainer: Color(0xFF251A00),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1E1B16),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1E1B16),
  surfaceVariant: Color(0xFFECE1CF),
  onSurfaceVariant: Color(0xFF4D4639),
  outline: Color(0xFF7E7667),
  onInverseSurface: Color(0xFFF7F0E7),
  inverseSurface: Color(0xFF33302A),
  inversePrimary: Color(0xFFF7BE00),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF775A00),
  //outlineVariant: Color(0xFFD0C5B4),
  //scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFF7BE00),
  onPrimary: Color(0xFF3F2E00),
  primaryContainer: Color(0xFF5A4300),
  onPrimaryContainer: Color(0xFFFFDF99),
  secondary: Color(0xFFD7C5A0),
  onSecondary: Color(0xFF3A2F15),
  secondaryContainer: Color(0xFF52452A),
  onSecondaryContainer: Color(0xFFF4E0BB),
  tertiary: Color(0xFFF7BE00),
  onTertiary: Color(0xFF3F2E00),
  tertiaryContainer: Color(0xFF5A4300),
  onTertiaryContainer: Color(0xFFFFDF99),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1E1B16),
  onBackground: Color(0xFFE9E1D9),
  surface: Color(0xFF1E1B16),
  onSurface: Color(0xFFE9E1D9),
  surfaceVariant: Color(0xFF4D4639),
  onSurfaceVariant: Color(0xFFD0C5B4),
  outline: Color(0xFF999080),
  onInverseSurface: Color(0xFF1E1B16),
  inverseSurface: Color(0xFFE9E1D9),
  inversePrimary: Color(0xFF775A00),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFF7BE00),
  //outlineVariant: Color(0xFF4D4639),
  //scrim: Color(0xFF000000),
);

/*
* Side Note: outlineVariant and scrim are commented out for now as current Material 3 framework does not support them
 */
