name: fm_mahanama_app
description: Official FM Mahanama client open-source app for mobile and web
publish_to: 'none' # Not publishing to pub.dev. Do not change this
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.2.0
  flutter_svg: ^1.1.6
  flutter_firebase_chat_core: ^1.6.4
  firebase_core: ^2.4.1
  shared_preferences: ^2.0.16
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  loader_overlay: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  animations: ^2.0.7
  flutter_native_splash: ^2.2.16
  just_audio: ^0.9.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/logos/fmm_logo.png
   - assets/logos/fmm_logo_background.png
